# Generated by Django 4.1.7 on 2023-02-25 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(db_index=True, max_length=100, verbose_name='Профессия')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='ДЦП очки')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=16, verbose_name='Имя пользователя')),
                ('level', models.IntegerField(verbose_name='Уровень персонажа')),
                ('pet', models.BooleanField(verbose_name='Питомец')),
                ('main', models.BooleanField(default=False, verbose_name='Основной персонаж')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='farm.role')),
                ('score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='farm.score')),
            ],
        ),
    ]
