# Generated by Django 4.1.7 on 2023-02-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
