# Generated by Django 4.1.7 on 2023-02-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_member_score_delete_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя РейдБосса')),
                ('level', models.PositiveIntegerField(default=70, verbose_name='Уровень РБ')),
                ('score', models.PositiveIntegerField(default=1, verbose_name='ДЦП очки')),
            ],
        ),
    ]
