# Generated by Django 4.1.7 on 2023-02-26 14:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_raidboss'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropRaidBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100, verbose_name='Книга')),
                ('weapon', models.CharField(max_length=100, verbose_name='Оружие')),
                ('accessoire', models.CharField(max_length=100, verbose_name='Бижа')),
                ('another', models.CharField(max_length=100, verbose_name='Другое')),
            ],
        ),
        migrations.AddField(
            model_name='raidboss',
            name='respawn',
            field=models.TimeField(default=datetime.time(11, 0), verbose_name='Время возрождения в минутах'),
        ),
        migrations.AlterField(
            model_name='raidboss',
            name='level',
            field=models.PositiveSmallIntegerField(default=70, verbose_name='Уровень РБ'),
        ),
        migrations.AlterField(
            model_name='raidboss',
            name='score',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='ДЦП очки'),
        ),
        migrations.CreateModel(
            name='FarmRaidBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Время убийства')),
                ('drop', models.ManyToManyField(blank=True, to='farm.dropraidboss')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='farm.raidboss', verbose_name='Имя рейд-босса')),
                ('party_members', models.ManyToManyField(blank=True, to='farm.member')),
            ],
        ),
    ]
