# Generated by Django 4.1.7 on 2023-02-26 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_user_remove_dropraidboss_accessoire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='character',
            field=models.ManyToManyField(to='farm.member', verbose_name='Персонаж'),
        ),
        migrations.AlterField(
            model_name='farmraidboss',
            name='drop',
            field=models.ManyToManyField(blank=True, to='farm.dropraidboss', verbose_name='Дроп'),
        ),
        migrations.AlterField(
            model_name='farmraidboss',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='farm.raidboss', verbose_name='Имя РейдБосса'),
        ),
    ]
