# Generated by Django 4.1.7 on 2023-02-26 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_rename_member_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raidboss',
            name='respawn',
        ),
        migrations.AddField(
            model_name='farmraidboss',
            name='respawn',
            field=models.TimeField(default=datetime.time(11, 0), verbose_name='Время возрождения'),
        ),
        migrations.AddField(
            model_name='raidboss',
            name='respawn_time',
            field=models.TimeField(default=datetime.time(11, 0), verbose_name='Время возрождения'),
        ),
        migrations.AlterField(
            model_name='farmraidboss',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время убийства'),
        ),
    ]
