# Generated by Django 4.1.7 on 2023-02-26 17:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_rename_respawn_time_raidboss_respawn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespawnTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.time(11, 0), verbose_name='Время возрождения')),
                ('raid_boss', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respawn_time', to='farm.raidboss')),
            ],
        ),
        migrations.AlterField(
            model_name='farmraidboss',
            name='respawn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='farm.respawntime', verbose_name='Время возрождения'),
        ),
    ]
