# Generated by Django 4.1.7 on 2023-02-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_respawntime_alter_farmraidboss_respawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respawntime',
            name='time',
            field=models.TimeField(verbose_name='Время возрождения'),
        ),
    ]
