# Generated by Django 4.1.7 on 2023-02-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_alter_respawntime_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmraidboss',
            name='respawn',
        ),
        migrations.AlterField(
            model_name='respawntime',
            name='raid_boss',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farm.raidboss', verbose_name='Имя РейдБосса'),
        ),
        migrations.AlterField(
            model_name='respawntime',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время возрождения'),
        ),
    ]
