# Generated by Django 4.1.7 on 2023-02-26 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_remove_farmraidboss_respawn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respawntime',
            name='raid_boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.raidboss', verbose_name='Имя РейдБосса'),
        ),
    ]
