# Generated by Django 4.1.7 on 2023-02-26 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_alter_respawntime_raid_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmraidboss',
            name='time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Время убийства'),
        ),
        migrations.AlterField(
            model_name='farmraidboss',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата убийства'),
        ),
    ]
