# Generated by Django 4.1.7 on 2023-02-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0017_farmraidboss_time_alter_farmraidboss_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': '2. Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='clanmember',
            options={'verbose_name': 'Киска и сосиска', 'verbose_name_plural': '1. Киски и сосиски'},
        ),
        migrations.AlterModelOptions(
            name='dropraidboss',
            options={'verbose_name_plural': '6. Дроп с РейдБоссов'},
        ),
        migrations.AlterModelOptions(
            name='farmraidboss',
            options={'verbose_name_plural': '5. Фарм РейдБоссов'},
        ),
        migrations.AlterModelOptions(
            name='raidboss',
            options={'verbose_name': 'РейдБосс', 'verbose_name_plural': '3. РейдБоссы'},
        ),
        migrations.AlterModelOptions(
            name='respawntime',
            options={'verbose_name_plural': '4. Респавн РейдБоссов'},
        ),
        migrations.AddField(
            model_name='raidboss',
            name='image',
            field=models.ImageField(default=1, upload_to='image', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raidboss',
            name='respawn',
            field=models.TimeField(verbose_name='Время возрождения'),
        ),
    ]
