# Generated by Django 4.1.7 on 2023-02-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0018_alter_character_options_alter_clanmember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidboss',
            name='image',
            field=models.ImageField(default='img.jpeg', upload_to='image', verbose_name='Изображение'),
        ),
    ]
