# Generated by Django 4.1.7 on 2023-03-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0019_alter_raidboss_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmraidboss',
            name='drop',
        ),
    ]
