# Generated by Django 4.1.7 on 2023-03-04 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0020_remove_farmraidboss_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='respawntime',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 4, 21, 7, 22, 92568), null=True, verbose_name='Дата возрождения'),
        ),
    ]
