# Generated by Django 4.1.7 on 2023-02-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_member_level_member_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.IntegerField(verbose_name='Уровень персонажа'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(max_length=16, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='member',
            name='pet',
            field=models.BooleanField(verbose_name='Питомец'),
        ),
        migrations.AlterField(
            model_name='role',
            name='profession',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Профессия'),
        ),
    ]
