# Generated by Django 4.1.7 on 2023-02-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_member_level_alter_member_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='twink',
            field=models.BooleanField(default=0, verbose_name='Твинк'),
            preserve_default=False,
        ),
    ]
