# Generated by Django 4.1.7 on 2023-02-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_member_twink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='twink',
        ),
        migrations.AddField(
            model_name='member',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Основной персонаж'),
        ),
    ]
